ECHO:
ECHO %HR%
ECHO Script:		%RUNSCRIPT%
ECHO SF Org:		%SFCONTEXT%
ECHO %HR%
ECHO Project:	!SFPROJECT!
ECHO Branche:	!GITBRANCH!
ECHO Workdir:	!WORKDIR!
ECHO GitStatus:	!GITSTATUS!
ECHO SFuser: 	%SFUSER%
ECHO Buildfile:	%BUILDXML%
ECHO AntLib:		%ANTLIB%
ECHO %HR%
ECHO:
